///* CODES FOR FLAGS, THAT ARE USED FOR MEMORY ALLOCATION *///

#define TILDE_FLAG -1
#define PERIOD_FLAG -2
#define MAC_TRUE_FLAG -5
#define IP4_TRUE_FLAG -6
#define BIT_FLAG 'b'
#define NUMBER_FLAG 'B'
#define HEXSTREAM_FLAG 'x'

