///* CODE FOR VARIOUS NODES *///

#define FUNCTION_NODE 1
#define VARIABLE_NODE 2
#define DATATYPE_NODE 3
#define RAW_VARIABLE_NODE 4
#define MEMBER_NODE 5
#define PACKET_NODE 6
#define EQUAL_NODE 7

#define PLUS_NODE 8
#define MINUS_NODE 9
#define LESSER_NODE 10
#define GREATER_NODE 11


